<a href="https://colab.research.google.com/github/aneelkumar18/NUMPY-/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. **Getting Familiar with NumPy**

   First, let’s cover the basics of NumPy, including creating arrays, performing basic operations, and understanding array properties.

In [2]:
#creating arrays
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", arr1d)
print("2D Array:\n", arr2d)
print("3D Array:\n", arr3d)

1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
#BASIC OPERATIONS

import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Element-wise addition
arr_sum = arr1d + 5

# Element-wise multiplication
arr_prod = arr1d * 2

print("Element-wise Addition:\n", arr_sum)
print("Element-wise Multiplication:\n", arr_prod)

Element-wise Addition:
 [ 6  7  8  9 10]
Element-wise Multiplication:
 [ 2  4  6  8 10]


In [4]:
#ARRAY PROPERTIES

import numpy as np
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

#shape of arr2d
print("Shape of arr2d:", arr2d.shape)

#data type of arr1d
print("Data type of arr1d:", arr1d.dtype)

#dimension of arr3d
print("Number of dimensions in arr3d:", arr3d.ndim)


Shape of arr2d: (2, 3)
Data type of arr1d: int64
Number of dimensions in arr3d: 3


**2. Data Manipulation**

   Now let’s write a Python program to demonstrate data manipulation with NumPy, including array creation, indexing, slicing, reshaping, and mathematical operations.

In [5]:
import numpy as np

# Creating an array
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Indexing
element = data[1, 2]
print("Element at [1, 2]:", element)

# Slicing
sub_array = data[0:2, 1:3]
print("Sliced Array:\n", sub_array)

# Reshaping
reshaped_data = data.reshape((1, 9))
print("Reshaped Data:\n", reshaped_data)

# Mathematical Operations
mean_value = np.mean(data)
sum_value = np.sum(data)
print("Mean Value:", mean_value)
print("Sum Value:", sum_value)


Element at [1, 2]: 60
Sliced Array:
 [[20 30]
 [50 60]]
Reshaped Data:
 [[10 20 30 40 50 60 70 80 90]]
Mean Value: 50.0
Sum Value: 450


**3. Data Aggregation**

   Data aggregation is a fundamental aspect of data analysis that involves summarizing or grouping data to derive meaningful insights. In NumPy, data aggregation functions allow you to compute summary statistics, perform group operations, and analyze data in various ways. Below

In [6]:
import numpy as np

# Sample data
data = np.array([15, 22, 35, 40, 55, 60, 72, 85, 90])

# statistical methods
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
total_sum = np.sum(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Sum:", total_sum)

# Grouping and aggregation
data_2d = np.array([[15, 22, 35], [40, 55, 60], [72, 85, 90]])
mean_per_row = np.mean(data_2d, axis=1)
print("Mean per row:\n", mean_per_row)

# Compute percentiles
percentiles = np.percentile(data, [25, 50, 75])
print("25th, 50th, and 75th Percentiles:", percentiles)


Mean: 52.666666666666664
Median: 55.0
Standard Deviation: 25.174943451332275
Sum: 474
Mean per row:
 [24.         51.66666667 82.33333333]
25th, 50th, and 75th Percentiles: [35. 55. 72.]


**4. Data Analysis**

   Perform data analysis using NumPy to find correlations, covariance and calculate percentiles

In [9]:
import numpy as np

# Sample data
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Correlation coefficient
data2 = np.array([9, 18, 29, 38, 51, 59, 68, 77, 88])
correlation = np.corrcoef(data, data2)[0, 1]
print("Correlation Coefficient:", correlation)

# Percentiles
percentiles = np.percentile(data, [25, 50, 75])
print("25th, 50th, and 75th Percentiles:", percentiles)


Correlation Coefficient: 0.9992171972185024
25th, 50th, and 75th Percentiles: [30. 50. 70.]


**5. Application in Data Science**

**Why NumPy is Useful:**

**Efficiency**: NumPy provides fast operations on large datasets due to its implementation in C and optimized mathematical functions.

**Convenience:** It offers a wide range of mathematical functions and array manipulation techniques that simplify complex computations.

**Integration**: NumPy arrays are compatible with many other scientific libraries in Python, such as SciPy, Pandas, and scikit-learn.

**Real-World Examples**:

**Machine Learning:** NumPy is used for handling large datasets, feature scaling, and implementing algorithms efficiently.

**Financial Analysis:** In finance, NumPy helps in risk analysis, portfolio management, and financial modeling by handling large numerical datasets.

**Scientific Research:** Researchers use NumPy for data analysis, simulations, and solving mathematical problems in fields like physics, biology, and engineering.